import { defineDocument, f, label } from '@daifuku/kernel';
import type { InvoiceTaxSummaryRow } from '@daifuku/mod-sales';

export const RestaurantClosing = defineDocument({
  name: 'restaurant_chain_closing',
  label: label('店舗の日次締め', 'Restaurant daily closings'),
  naming: { type: 'sequence', prefix: 'RDAY-', period: 'year' },
  fields: {
    storeId: f.ref('restaurant_chain_store', { label: label('店舗', 'Store'), required: true, immutable: true }),
    date: f.date({ label: label('営業日', 'Business date'), required: true, default: 'today', index: true }),
    cashAmount: f.money({
      label: label('現金売上（税込）', 'Cash sales incl. tax'),
      required: true,
      default: '0',
      min: '0',
    }),
    cardAmount: f.money({
      label: label('カード売上（税込・未入金）', 'Card sales, awaiting settlement'),
      required: true,
      default: '0',
      min: '0',
    }),
    qrAmount: f.money({
      label: label('QR売上（税込・未入金）', 'QR sales, awaiting settlement'),
      required: true,
      default: '0',
      min: '0',
    }),
    dayStatus: f.enum(['sales', 'no_sales', 'closed'], {
      label: label('営業実績区分', 'Day status'),
      required: true,
      default: 'sales',
      labels: {
        sales: label('売上あり', 'Sales'),
        no_sales: label('売上ゼロ営業', 'Open with no sales'),
        closed: label('休業', 'Closed'),
      },
    }),
    cashSalesCounted: f.money({
      label: label('現金売上の実収額（釣銭準備金等を除く）', 'Counted cash sales'),
      min: '0',
    }),
    reviewStatus: f.enum(['draft', 'submitted', 'approved', 'returned'], {
      label: label('提出・確認状態', 'Review status'),
      required: true,
      default: 'draft',
      serverOwned: true,
      labels: {
        draft: label('未提出', 'Draft'),
        submitted: label('店長確認待ち', 'Awaiting review'),
        approved: label('本部確定待ち', 'Awaiting finalization'),
        returned: label('差戻し', 'Returned'),
      },
    }),
    submittedAt: f.timestamp({ label: label('提出日時', 'Submitted at'), serverOwned: true }),
    submittedBy: f.text({ label: label('提出者', 'Submitted by'), serverOwned: true }),
    reviewedAt: f.timestamp({ label: label('確認日時', 'Reviewed at'), serverOwned: true }),
    reviewedBy: f.text({ label: label('確認者', 'Reviewed by'), serverOwned: true }),
    reviewNote: f.text({ label: label('確認・差戻し理由', 'Review note'), maxLength: 1000, serverOwned: true }),
    subtotal: f.money({ label: label('税抜売上', 'Net sales'), serverOwned: true, required: true, default: '0' }),
    taxTotal: f.money({ label: label('消費税額', 'Tax'), serverOwned: true, required: true, default: '0' }),
    total: f.money({ label: label('税込売上', 'Gross sales'), serverOwned: true, required: true, default: '0' }),
    quantity: f.quantity({ label: label('販売数', 'Servings sold'), serverOwned: true, required: true, default: '0' }),
    taxSummary: f.json<InvoiceTaxSummaryRow[]>({ label: label('税率別内訳', 'Tax breakdown'), serverOwned: true }),
    consumptionCost: f.money({
      label: label('材料消費原価', 'Ingredient consumption cost'),
      serverOwned: true,
      required: true,
      default: '0',
      scale: 6,
    }),
    wasteCost: f.money({
      label: label('材料廃棄原価', 'Ingredient waste cost'),
      serverOwned: true,
      required: true,
      default: '0',
      scale: 6,
    }),
    salesInvoiceId: f.ref('sales_invoice', { label: label('売上請求書', 'Sales invoice'), serverOwned: true }),
    paymentId: f.ref('payment', { label: label('現金入金', 'Cash receipt'), serverOwned: true }),
    consumptionEntryId: f.ref('stock_entry', { label: label('材料消費出庫', 'Ingredient issue'), serverOwned: true }),
    wasteEntryId: f.ref('stock_entry', { label: label('材料廃棄出庫', 'Waste issue'), serverOwned: true }),
    cancelledDate: f.date({ label: label('取消有効日', 'Cancellation effective date'), serverOwned: true }),
    note: f.text({ label: label('備考', 'Notes'), multiline: true, maxLength: 1000 }),
  },
  allowOnSubmit: ['salesInvoiceId', 'paymentId', 'consumptionEntryId', 'wasteEntryId', 'consumptionCost', 'wasteCost'],
  lines: [
    { entity: 'restaurant_chain_closing_line', parentField: 'closingId' },
    { entity: 'restaurant_chain_waste_line', parentField: 'closingId' },
  ],
  indexes: [['storeId', 'date']],
  storeAccess: { kind: 'store', field: 'storeId' },
  permissions: {
    roles: {
      chain_staff: ['read', 'export', 'create', 'update', 'delete'],
      chain_manager: ['read', 'export', 'create', 'update', 'delete'],
      sales: ['read', 'export', 'create', 'update', 'delete', 'submit', 'cancel', 'amend'],
      inventory: ['read', 'export'],
      accounting: ['read', 'export'],
      viewer: ['read', 'export'],
    },
  },
  views: {
    list: ['storeId', 'date', 'dayStatus', 'reviewStatus', 'total', 'cashAmount', 'cardAmount', 'qrAmount'],
    form: [
      ['storeId', 'date', 'dayStatus'],
      ['reviewStatus', 'submittedAt', 'reviewedAt'],
      ['cashSalesCounted'],
      ['cashAmount', 'cardAmount', 'qrAmount'],
      ['subtotal', 'taxTotal', 'total'],
      ['consumptionCost', 'wasteCost'],
      ['note'],
    ],
  },
});
