// UI chrome strings (labels that do not come from /meta). Both languages always (docs/conventions/code-style.md).
import type { Label } from './api/types.ts';

const L = (ja: string, en: string): Label => ({ ja, en });

export const S = {
  appName: L('大福帳', 'Daifuku'),
  login: L('ログイン', 'Log in'),
  loggingIn: L('ログイン中…', 'Logging in…'),
  logout: L('ログアウト', 'Log out'),
  email: L('メールアドレス', 'Email'),
  password: L('パスワード', 'Password'),
  loginFailed: L('ログインに失敗しました', 'Login failed'),
  allEntities: L('すべてのエンティティ', 'All entities'),
  menu: L('メニュー', 'Menu'),
  home: L('ホーム', 'Home'),
  loading: L('読み込み中…', 'Loading…'),
  loadFailed: L('読み込みに失敗しました', 'Failed to load'),
  retry: L('再試行', 'Retry'),
  unknownEntity: L(
    'このエンティティは存在しないか、閲覧権限がありません。',
    'This entity does not exist or you may not read it.',
  ),
  search: L('検索', 'Search'),
  searchPlaceholder: L('検索…', 'Search…'),
  new: L('新規', 'New'),
  noRows: L('該当するデータがありません', 'No records'),
  total: L('件', 'total'),
  page: L('ページ', 'Page'),
  prev: L('前へ', 'Prev'),
  next: L('次へ', 'Next'),
  save: L('保存', 'Save'),
  saving: L('保存中…', 'Saving…'),
  saved: L('保存しました', 'Saved'),
  created: L('作成しました', 'Created'),
  deleted: L('削除しました', 'Deleted'),
  cancel: L('キャンセル', 'Cancel'),
  back: L('一覧へ戻る', 'Back to list'),
  edit: L('編集', 'Edit'),
  delete: L('削除', 'Delete'),
  confirmDelete: L('このレコードを削除しますか？', 'Delete this record?'),
  required: L('必須', 'required'),
  requiredFieldMissing: L('必須項目です', 'This field is required'),
  formHasErrors: L('入力内容を確認してください', 'Please check the highlighted fields'),
  submit: L('確定', 'Submit'),
  cancelDoc: L('取消', 'Cancel'),
  amend: L('訂正', 'Amend'),
  confirmSubmit: L(
    'この伝票を確定しますか？確定後は編集できなくなります。',
    'Submit this document? Most fields lock after submit.',
  ),
  confirmCancel: L('この伝票を取消しますか？', 'Cancel this document?'),
  submitted: L('確定しました', 'Submitted'),
  cancelled: L('取消しました', 'Cancelled'),
  amended: L('訂正用の下書きを作成しました', 'Amendment draft created'),
  docstatus: L('状態', 'Status'),
  number: L('番号', 'Number'),
  amendedFrom: L('訂正元', 'Amended from'),
  audit: L('監査ログ', 'Audit'),
  auditEmpty: L('監査ログはありません', 'No audit entries'),
  auditOp: L('操作', 'Op'),
  auditActor: L('実行者', 'Actor'),
  auditAt: L('日時', 'At'),
  auditChanged: L('変更項目', 'Changed fields'),
  conflictTitle: L('他のユーザーが先に更新しました', 'Someone else updated this record'),
  conflictBody: L(
    '最新の内容を読み込み直してから、もう一度編集してください。',
    'Reload the latest version, then re-apply your changes.',
  ),
  reload: L('再読み込み', 'Reload'),
  version: L('バージョン', 'Version'),
  createdAt: L('作成日時', 'Created at'),
  updatedAt: L('更新日時', 'Updated at'),
  id: L('ID', 'ID'),
  selectNone: L('（未選択）', '(none)'),
  refSearch: L('名称で検索…', 'Search by name…'),
  refNoMatch: L('該当なし', 'No matches'),
  clear: L('クリア', 'Clear'),
  jsonHint: L('JSON 形式で入力', 'Enter JSON'),
  readonly: L('読み取り専用', 'read-only'),
  errorTitle: L('エラー', 'Error'),
  networkHint: L('API に接続できません', 'Cannot reach the API'),
  notFound: L('ページが見つかりません', 'Page not found'),
  close: L('閉じる', 'Close'),
  language: L('言語', 'Language'),
  sessionExpired: L('セッションが切れました。再度ログインしてください。', 'Your session expired. Please log in again.'),
  // web-phase1: line grids (AC-1/2)
  lines: L('明細', 'Lines'),
  addRow: L('行を追加', 'Add row'),
  removeRow: L('行を削除', 'Remove row'),
  moveUp: L('上へ', 'Move up'),
  moveDown: L('下へ', 'Move down'),
  rowNo: L('#', '#'),
  sums: L('合計', 'Total'),
  referenceValue: L('参考値', 'reference'),
  referenceValueHint: L(
    '画面上の合算です。正式な値はサーバが計算します。',
    'Computed on this screen; the server value is authoritative.',
  ),
  noLines: L('明細がありません', 'No lines'),
  linesFrozen: L('確定済み／取消済みのため明細は変更できません', 'Lines are frozen after submit/cancel'),
  linesHaveErrors: L('明細の入力内容を確認してください', 'Please check the highlighted line cells'),
  enterAddsRow: L('Enter: 次の行 / 最終行では追加', 'Enter: next row / adds a row on the last one'),
  // reports (AC-3)
  reports: L('レポート', 'Reports'),
  run: L('実行', 'Run'),
  running: L('実行中…', 'Running…'),
  downloadCsv: L('CSV ダウンロード', 'Download CSV'),
  reportEmpty: L('該当する行がありません', 'No rows'),
  reportTruncated: L('行数が上限を超えたため一部のみ表示しています', 'Row limit reached; showing a partial result'),
  reportNotFound: L(
    'このレポートは存在しないか、実行権限がありません。',
    'This report does not exist or you may not run it.',
  ),
  reportRows: L('行', 'rows'),
  conditions: L('条件', 'Conditions'),
  // attachments (AC-4)
  attachments: L('添付', 'Attachments'),
  attachmentsEmpty: L('添付はありません', 'No attachments'),
  upload: L('アップロード', 'Upload'),
  uploading: L('アップロード中…', 'Uploading…'),
  uploaded: L('アップロードしました', 'Uploaded'),
  file: L('ファイル', 'File'),
  fileRequired: L('ファイルを選択してください', 'Choose a file'),
  kind: L('種別', 'Kind'),
  txnDate: L('取引年月日', 'Transaction date'),
  amount: L('取引金額', 'Amount'),
  partner: L('取引先', 'Partner'),
  note: L('メモ', 'Note'),
  download: L('ダウンロード', 'Download'),
  size: L('サイズ', 'Size'),
  superseded: L('訂正済', 'superseded'),
  // settings (AC-5)
  settings: L('設定', 'Settings'),
  settingsEmpty: L('モジュールが宣言した設定はありません', 'No module has declared settings'),
  settingsForbidden: L(
    '設定の変更には admin または settings ロールが必要です。',
    'Changing settings requires the admin or settings role.',
  ),
  settingSaved: L('設定を保存しました', 'Setting saved'),
  key: L('キー', 'Key'),
  rawJson: L('JSON で編集', 'Edit as JSON'),
  // web-polish: print view
  viewInvoice: L('請求書を表示', 'View invoice'),
  print: L('印刷', 'Print'),
  rendering: L('帳票を作成しています…', 'Rendering…'),
  popupBlocked: L(
    '新しいタブを開けませんでした。ポップアップを許可してください。',
    'Could not open a new tab. Please allow pop-ups for this site.',
  ),
  printNoHtml: L('帳票の HTML が返されませんでした', 'The action returned no HTML'),
  // web-polish: home dashboard
  documents: L('伝票', 'Documents'),
  masters: L('マスタ', 'Masters'),
  list: L('一覧', 'List'),
  countUnavailable: L('件数を取得できませんでした', 'Count unavailable'),
  noDocuments: L(
    '伝票エンティティがありません。左のメニューからエンティティを選んでください。',
    'No document entities. Pick an entity from the menu on the left.',
  ),
  // web-phase15: ext fields (AC-3)
  extFields: L('追加項目', 'Additional fields'),
  // web-phase15: allocation picker (AC-1/AC-2)
  pickOutstanding: L('未消込の請求書から選ぶ', 'Pick from outstanding invoices'),
  pickOutstandingNeedsHeader: L('区分と取引先を入力すると選べます', 'Enter the direction and partner first'),
  outstandingInvoices: L('未消込の請求書', 'Outstanding invoices'),
  outstandingEmpty: L('未消込の請求書はありません', 'No outstanding invoices'),
  allocatedTotal: L('配分合計', 'Allocated'),
  unallocated: L('未配分', 'Unallocated'),
  overAllocated: L('配分合計が金額を超えています', 'Allocations exceed the amount'),
  submitBlockedOverAllocated: L(
    '配分合計が金額を超えているため確定できません',
    'Cannot submit: allocations exceed the amount',
  ),
  date: L('日付', 'Date'),
  dueDate: L('期日', 'Due date'),
  balance: L('残高', 'Balance'),
  allocationAmount: L('消込額', 'Amount'),
  select: L('選択', 'Select'),
  alreadyAllocated: L('追加済み', 'Added'),
  addSelected: L('選択した請求書を追加', 'Add selected'),
  allocationsAdded: L('消込明細に追加しました', 'Added to the allocations'),
  pickInvalid: L('数値を入力してください', 'Enter a number'),
  pickNotPositive: L('0 より大きい額にしてください', 'Must be greater than 0'),
  pickOverBalance: L('残高を超えています', 'Exceeds the balance'),
} as const;
