import { useLocale } from '../i18n.tsx';
const english: Record<string, string> = {
  '0件': '0 records',
  '01 · 科目の対応付け': '01 · Account mapping',
  '02 · 消去と調整': '02 · Eliminations and adjustments',
  '1. 対象会社と会計期間': '1. Companies and fiscal period',
  '1. 精算契約を選択': '1. Choose an agreement',
  '2. 入出金を確認': '2. Review settlement',
  '2. 科目対応・消去を入力': '2. Map accounts and enter eliminations',
  FC月次精算: 'Monthly franchise settlement',
  'FC月次精算を作成・請求確定': 'Create and post a franchise invoice',
  FC未決済残高の入出金: 'Settle the outstanding franchise balance',
  'FC精算・入出金・請求を取消': 'Cancel franchise settlement, payment and invoice',
  'JPY・同じ会計期間の会社を選択。単体試算表を確認してから下書きへ進みます。':
    'Choose JPY companies with matching fiscal periods. Review standalone sources before creating a draft.',
  POS原資料を再試行: 'Retry POS source',
  POS原資料を訂正: 'Correct POS source',
  POS決済の自動連携: 'Automatic POS payment integration',
  Square加盟店: 'Square merchant',
  'Square通知から決済原資料と仮勘定仕訳を作成。受信・保留・再試行・訂正の状況を追跡します。':
    'Create payment evidence and clearing entries from Square notifications. Track receipt, deferral, retries and corrections.',
  '。既存の請求書により消費税を計算します。': '. The invoice workflow calculates tax.',
  'この会社でこの操作を利用する権限がありません。': 'You do not have permission for this operation in this company.',
  この契約で月次精算: 'Settle this agreement',
  この調整を削除: 'Remove this adjustment',
  その他: 'Other',
  'まだ通知を受信していません。未設定の連携を稼働中とは表示しません。':
    'No notifications have arrived. An unconfigured integration is not shown as operational.',
  グループ連結精算表: 'Group consolidation worksheet',
  一覧のページ: 'List pages',
  下書き: 'Draft',
  '下書きを編集・資料更新': 'Edit draft and refresh sources',
  仕訳: 'Journal entry',
  仕訳行を追加: 'Add journal line',
  '会社 / 単体科目': 'Company / standalone account',
  '会社別の試算表を集め、科目の対応付けと消去・調整を確認します。各会社への現在の権限を毎回確認します。':
    'Collect trial balances and review account mappings, eliminations and adjustments. Current access to every company is checked each time.',
  会社別科目を対応付けて連結下書きを作成: 'Map company accounts and prepare a consolidation draft',
  '会社間の二重転記ではなく、この会社の請求・支払請求を作成します。対象月全体が契約期間内である必要があります。売上資料を自動検証・POSから税抜推定する機能は含みません。':
    'This creates an invoice or bill in the current company only. The entire month must be covered by the agreement. Sales declarations are reviewed manually; net sales are not inferred from POS payments.',
  '保存した根拠・消去明細を確認': 'Review saved evidence and eliminations',
  保存した精算表: 'Saved worksheets',
  '保存した精算表はまだありません。': 'No worksheets have been saved.',
  保存時点で対象以前の全期間締め済み: 'All contributing periods were closed at capture',
  保存時点で未締め期間あり: 'Some contributing periods were open at capture',
  '保存資料の閲覧権限を確認しています…': 'Checking access to saved sources…',
  '借方・貸方はサーバーで一致確認': 'Debit and credit balance verified by the server',
  '借方（円）': 'Debit (JPY)',
  借方: 'Debit',
  停止中: 'Inactive',
  '元帳 / 訂正': 'Ledger / correction',
  元決済待ち: 'Awaiting original payment',
  '先頭100店舗を表示しています。全店舗は店舗設定から確認できます。':
    'Showing the first 100 locations. Open location settings to view all locations.',
  入出金を確定: 'Confirm payment',
  入出金を確認: 'View payment',
  入出金日: 'Payment date',
  入出金生成済み: 'Payment generated',
  入出金科目: 'Cash or bank account',
  '入出金科目の選択権限がありません。': 'You cannot select a payment account.',
  '入出金科目を候補から選択してください。': 'Select a payment account from the suggestions.',
  '全社の対象・期首残高に関係する期間が締め済みで、保存後の単体資料が変わっていないことを再検証します。締めた直後は下書きを更新してください。':
    'Confirmation verifies that all contributing periods are closed and sources are unchanged. Refresh the draft after closing periods.',
  内部取引の消去: 'Intercompany elimination',
  再試行: 'Retry',
  分類: 'Classification',
  '初版はJPYの完了決済・返金の連携です。決済金額から売上税・品目・在庫を推測しません。決済未収等と未分類売上の仮勘定へ転記し、実売上との照合・振替は会計担当が別途行います。':
    'This release supports completed JPY payments and refunds. It does not infer sales tax, items or inventory. Entries use settlement assets and unclassified proceeds; accounting staff separately reconcile and reclassify actual sales.',
  '利用権限を確認しています…': 'Checking permissions…',
  前へ: 'Previous',
  加盟店へ請求: 'Invoice franchisee',
  '加盟店・外部店舗・会社は運用設定と一致する必要があります。Webhook署名キーはブラウザへ送りません。':
    'Merchant, external location and company must match operational configuration. Webhook signing keys never enter the browser.',
  区分: 'Type',
  単体合算: 'Standalone total',
  '単体帳簿は変更しません。金額は保存時にサーバーで再取得・計算され、確定前に結果を確認できます。':
    'Standalone books remain unchanged. Saving refreshes and calculates server-side sources; review the result before confirming.',
  単体残高: 'Standalone balance',
  '単体残高 ＋ 消去 ＋ 調整': 'Standalone balances + eliminations + adjustments',
  単体資料を取得: 'Load standalone sources',
  原資料: 'Source',
  '原資料日 / 外部ID': 'Source date / external ID',
  収益: 'Revenue',
  '取引先と契約条件を登録すると、月次精算を開始できます。':
    'Register a partner and agreement terms to begin monthly settlement.',
  取消: 'Cancel',
  '取消は元帳を削除せず訂正日の逆仕訳を作ります。元決済の取消は先に返金を取り消す必要があります。':
    'Corrections retain the ledger and post a dated reversal. Reverse refunds before correcting their original payment.',
  '取消後も保存資料・消去・調整は履歴に残ります。単体帳簿には変更を加えません。':
    'Cancellation retains sources, eliminations and adjustments in history. Standalone books remain unchanged.',
  取消有効日: 'Cancellation effective date',
  '取消有効日・理由': 'Cancellation date and reason',
  取消済み: 'Cancelled',
  取消理由: 'Cancellation reason',
  受信と再処理: 'Inbox and retries',
  受信済み: 'Received',
  受信状態: 'Inbox status',
  '各社の勘定科目を連結科目へ対応付けます。同じ連結コードには同じ名称・分類を指定してください。借方残は正、貸方残は負で表示します。':
    "Map each company's accounts to group accounts. A group code must have one name and classification. Debit balances are positive; credit balances are negative.",
  '各調整の借方・貸方が一致する必要があります。推測した資本連結・税効果等は自動生成しません。':
    'Every adjustment must balance. Capital consolidation and tax effects are not inferred or automatically generated.',
  '同じ契約・同じ月の再実行で二重請求は作りません。訂正は理由を残して取消し、改めて作成します。':
    'Repeating the same agreement and month does not duplicate invoices. Record a reason, cancel and create a new settlement to correct it.',
  売上資料: 'Sales evidence',
  外部原資料ID: 'External source ID',
  契約: 'Agreement',
  '契約による精算料（税抜）': 'Contractual fee before tax',
  契約を管理: 'Manage agreements',
  '契約条件と確定売上資料を固定してロイヤリティを計算し、請求・入出金・取消まで一つの根拠でつなぎます。':
    'Snapshot agreement terms and approved sales to calculate royalties and trace invoicing, payment and cancellation to the same evidence.',
  対象: 'Companies',
  '対象会社の判断、内部取引照合表、調整の承認記録など':
    'Basis for included companies, intercompany reconciliations and adjustment approvals',
  '対象会社の閲覧権限が失効した資料は開けません。':
    'Saved worksheets cannot be opened after access to an included company is revoked.',
  対象期間: 'Period',
  店舗: 'Location',
  '店舗 / 種別': 'Location / type',
  店舗設定を開く: 'Open location settings',
  '承認済み月次売上表の番号、照合日、確認担当など':
    'Approved sales statement reference, reconciliation date and reviewer',
  振込: 'Bank transfer',
  '摘要・根拠': 'Description and evidence',
  操作: 'Action',
  支払期日: 'Due date',
  支払請求: 'Payable bill',
  方向: 'Direction',
  方法: 'Method',
  最新の状態を確認: 'Refresh current state',
  最新の状況を取得: 'Refresh integration status',
  '最新の精算・残高を取得しています…': 'Loading current settlement and balance…',
  月: 'Month',
  月次精算の履歴: 'Monthly settlement history',
  '月次精算はまだありません。': 'No monthly settlements yet.',
  有効: 'Active',
  '未完了・対象外': 'Not completed / ignored',
  未対応イベント: 'Unsupported event',
  '未締め期間があります。下書きは作成できます。': 'Some periods are open. You can still create a draft.',
  本部への支払請求: 'Bill payable to franchisor',
  根拠と残高: 'Evidence and balance',
  根拠を確認して請求を生成: 'Review evidence and generate invoice',
  次へ: 'Next',
  '残高は借方が正・貸方が負です。期間損益や法定連結財務諸表を自動生成したものではありません。':
    'Debit balances are positive and credit balances negative. This is not an automatically generated period income statement or statutory consolidated financial statement.',
  残高を再取得: 'Refresh balance',
  決済: 'Payment',
  消去: 'Elimination',
  照合資料と下書きを保存: 'Save evidence and draft',
  状態: 'Status',
  現在の未決済残高: 'Current outstanding balance',
  '現在の未決済残高全額を消し込みます。入出金科目・日付を確認してください。':
    'The current outstanding balance will be allocated in full. Review the payment account and date.',
  '現在の権限で利用できるJPY会社がありません。': 'No JPY companies are available with your current permissions.',
  現在の設定で再試行: 'Retry with current configuration',
  現金: 'Cash',
  理由を記録して一括取消: 'Record reason and cancel together',
  理由を記録して取消: 'Record reason and cancel',
  理由を記録して逆仕訳: 'Record reason and reverse',
  '確定・取消理由:': 'Confirmation / cancellation reason:',
  確定内容を確認: 'Review confirmation',
  '確定売上資料・確認記録': 'Approved sales evidence and review record',
  確定済み: 'Confirmed',
  確認が必要: 'Review required',
  '確認が必要・元決済待ちは転記成功ではありません。エラーの原因を修正し、再試行してください。':
    'Review-required and awaiting-payment states do not mean posting succeeded. Resolve the cause and retry.',
  確認して確定: 'Review and confirm',
  '確認・取消理由': 'Confirmation / cancellation reason',
  確認事項: 'Review notes',
  税抜売上: 'Net sales',
  '税抜売上（円）': 'Net sales (JPY)',
  '税込 / 税抜売上': 'Gross / net sales',
  '税込・税抜の基準、率、定額、丸め、税区分は契約ごとに指定します。使用済み契約は変更せず、新期間の契約を追加してください。':
    'Each agreement specifies gross/net basis, rate, fixed fee, rounding and tax category. Create a new agreement for future terms once an agreement has been used.',
  税込売上: 'Gross sales',
  '税込売上（円）': 'Gross sales (JPY)',
  税込額: 'Gross amount',
  精算を取消: 'Cancel settlement',
  精算月: 'Settlement month',
  精算状態: 'Settlement status',
  精算表の名前: 'Worksheet name',
  精算表の状態: 'Worksheet status',
  精算表を開く: 'Open worksheet',
  純資産: 'Equity',
  終了日: 'End date',
  行削除: 'Remove line',
  行: 'Line',
  訂正: 'Correct',
  '訂正後に同じ通知を再送しても再転記されません。実際の決済取消はSquare側の返金手続きが必要です。':
    'Replaying a corrected source does not repost it. Actual payment refunds must be initiated in Square.',
  訂正日: 'Correction date',
  訂正理由: 'Correction reason',
  試行: 'Attempts',
  調整: 'Adjustment',
  請求: 'Invoice',
  請求日: 'Invoice date',
  請求書: 'Invoice',
  請求書を確認: 'View invoice',
  請求生成済み: 'Invoice generated',
  請求税込額: 'Invoice total including tax',
  負債: 'Liability',
  '貸方（円）': 'Credit (JPY)',
  貸方: 'Credit',
  費用: 'Expense',
  資産: 'Asset',
  転記した決済原資料: 'Posted payment sources',
  転記済み: 'Posted',
  返金: 'Refund',
  '連動した入出金を戻してから請求を取り消します。外部で消し込んだ入出金が残る場合は原資料を整理するまで取消できません。':
    'The linked payment is reversed before the invoice. Resolve any remaining externally created allocations before cancellation.',
  連動入出金: 'Linked payment',
  連動入出金生成済み: 'Linked payment generated',
  連携店舗: 'Integration locations',
  '連携店舗を作成し、運用担当がSquare通知先・署名キー・専用利用者を設定してください。':
    'Create a location and ask the operator to configure the Square callback, signing key and dedicated user.',
  連結コード: 'Group code',
  連結修正: 'Consolidation adjustment',
  連結借方合計: 'Consolidated debit total',
  連結残高: 'Consolidated balance',
  連結科目: 'Group account',
  連結科目名: 'Group account name',
  '連結範囲・根拠資料・確認事項': 'Consolidation scope, evidence and review notes',
  連結精算表: 'Consolidation worksheet',
  連結精算表の下書きを編集: 'Edit consolidation draft',
  連結精算表を取消: 'Cancel consolidation worksheet',
  連結精算表を確定: 'Confirm consolidation worksheet',
  連結貸方合計: 'Consolidated credit total',
  選択してください: 'Select an account',
  '重複通知は同じ原資料へ結び付きます。処理できない場合は保留状態とエラーが残ります。':
    'Duplicate notifications link to the existing source. Failed processing retains an explicit deferred or blocked state and error.',
  金額: 'Amount',
  開始日: 'Start date',
  '＋ 消去・調整を追加': '+ Add elimination or adjustment',
  '社・': ' companies · ',
  '科目を取得。': ' accounts loaded. ',
  '対象以前の全期間が締め済みです。': 'All contributing periods are closed.',
  '社 · JPY': ' companies · JPY',
  '基準 · 率': ' basis · rate ',
  消費税: 'Tax ',
  '円 · 請求書計算値': ' JPY · calculated by invoice',
  入出金済: 'Paid ',
  円: ' JPY',
  '請求 ·': ' invoiced · ',
  期日: ' due',
  '· 単体帳簿は変更しません': ' · Standalone books are unchanged',
  '· 借方': ' · Debit ',
  '/ 貸方': ' / Credit ',
  基準: ' basis',
  科目: 'Account',
  '× 率': ' × rate ',
  '＋ 定額': ' + fixed fee ',
  '· 現在残高': ' · Current balance ',
  '/ 店舗': ' / Location ',
};
export function commerceCopy(value: string, locale: string): string {
  if (locale !== 'en') return value;
  const key = value.trim(),
    translated = english[key];
  return translated === undefined
    ? value
    : value.slice(0, value.length - value.trimStart().length) + translated + value.slice(value.trimEnd().length);
}
export function useCommerceCopy() {
  const { locale } = useLocale();
  return (value: string) => commerceCopy(value, locale);
}
