import { useState } from 'react';
import { formText, type PayrollSummary } from '../api/workforce.ts';
import { useWorkforceTask } from '../api/workforce-query.ts';
import { useLocale } from '../i18n.tsx';
import { formatDecimal } from '../lib/format.ts';
import { deductionLabels, minutesLabel } from '../lib/workforce.ts';
import { StatutoryPayrollConfirm } from './fiscal-payroll.tsx';
import { WorkforceDialog } from './workforce-dialog.tsx';
import { WorkforceCalculation } from './workforce-calculation.tsx';
import { WorkforceEmpty, WorkforceMoney, WorkforcePanel, WorkforceStatus } from './workforce-shared.tsx';

export function PayrollBreakdown({ row }: { row: PayrollSummary }) {
  const { t, locale } = useLocale();
  return <><dl className="workforce-definition"><div><dt>{t({ ja: '基本給', en: 'Base pay' })}</dt><dd><WorkforceMoney value={row.basePay} /></dd></div><div><dt>{t({ ja: '割増賃金', en: 'Premium pay' })}</dt><dd><WorkforceMoney value={row.premiumPay} /></dd></div><div><dt>{t({ ja: '労働時間', en: 'Worked time' })}</dt><dd>{minutesLabel(row.workedMinutes, locale)}</dd></div><div><dt>{t({ ja: '有給取得', en: 'Paid leave taken' })}</dt><dd>{formatDecimal(row.paidLeaveDays)} {t({ ja: '日', en: 'days' })}</dd></div></dl>
    {row.allowances.length ? <div className="workforce-record-list">{row.allowances.map((item, i) => <div className="workforce-record" key={i}><header><h3>{item.name}</h3><WorkforceMoney value={item.amount} /></header><p>{item.basis}</p></div>)}</div> : null}
    {row.deductions.length ? <div className="workforce-record-list">{row.deductions.map((item) => <div className="workforce-record" key={item.kind}><header><h3>{t(deductionLabels[item.kind])}</h3><WorkforceMoney value={item.amount} /></header><p>{item.basis}</p></div>)}</div> : null}
    <dl className="workforce-definition"><div><dt>{t({ ja: '総支給額', en: 'Gross pay' })}</dt><dd><WorkforceMoney value={row.grossPay} /></dd></div><div><dt>{t({ ja: '控除合計', en: 'Total deductions' })}</dt><dd><WorkforceMoney value={row.deductionTotal} /></dd></div></dl>
    {row.status === 'confirmed' ? <div className="workforce-pay-total"><span>{t({ ja: '差引支給額', en: 'Net pay' })}</span><WorkforceMoney value={row.netPay} /></div> : <p className="workforce-notice">{t({ ja: '計算中の金額です。控除・手当・計算根拠を確認して確定するまで、本人には公開されません。', en: 'These amounts are provisional. They are not visible to the employee until deductions, allowances and calculations are reviewed and confirmed.' })}</p>}
    <WorkforceCalculation row={row} />
  </>;
}

function PayrollConfirm({ row, current, onClose }: { row: PayrollSummary; current: PayrollSummary | undefined; onClose: () => void }) {
  const { t } = useLocale(), task = useWorkforceTask();
  const [allowances, setAllowances] = useState(0);
  if (row.calculation.statutory) return <StatutoryPayrollConfirm row={row} current={current} onClose={onClose}><PayrollBreakdown row={row} /></StatutoryPayrollConfirm>;
  return <WorkforceDialog title={t({ ja: '給与明細を確認・確定', en: 'Review and confirm payroll' })} description={row.employeeName + ' · ' + row.period + ' / ' + t({ ja: '各控除を資料に基づいて確認します。対象外の項目も「0」と対象外の根拠を明示してください。', en: 'Verify every deduction against evidence. For non-applicable items, enter 0 and explain why.' })} submitLabel={t({ ja: '確認して給与を確定', en: 'Confirm payroll' })} stale={current?.version !== row.version} onClose={onClose} onSubmit={async (data) => {
    await task.mutateAsync({ action: 'workforce.confirm_payroll', input: { payrollId: row.id, expectedVersion: row.version, deductions: Object.keys(deductionLabels).map((kind) => ({ kind, amount: formText(data, kind + '.amount'), basis: formText(data, kind + '.basis'), confirmed: data.get(kind + '.confirmed') === 'on' })), allowances: Array.from({ length: allowances }, (_, i) => ({ name: formText(data, `allowance${i}.name`), amount: formText(data, `allowance${i}.amount`), basis: formText(data, `allowance${i}.basis`) })), calculationConfirmed: data.get('calculationConfirmed') === 'on', reason: formText(data, 'reason') } });
  }}><PayrollBreakdown row={row} />
    {Object.entries(deductionLabels).map(([kind, label]) => <section className="workforce-deduction" key={kind}><h3>{t(label)}</h3><div className="workforce-form-row"><label>{t(label)} {t({ ja: '金額（円）', en: 'amount (JPY)' })}<input className="input" name={kind + '.amount'} inputMode="numeric" pattern="[0-9]+" required /></label><label>{t(label)} {t({ ja: '根拠', en: 'basis' })}<input className="input" name={kind + '.basis'} maxLength={1000} required /></label></div><label className="workforce-checkbox"><input type="checkbox" name={kind + '.confirmed'} required />{t(label)}{t({ ja: 'を確認しました', en: ' verified' })}</label></section>)}
    <section className="workforce-deduction"><h3>{t({ ja: '追加の手当', en: 'Additional allowances' })}</h3>{Array.from({ length: allowances }, (_, i) => <div className="workforce-form-fields" key={i}><label>{t({ ja: '手当の名称', en: 'Allowance name' })} {i + 1}<input className="input" name={`allowance${i}.name`} required maxLength={100} /></label><div className="workforce-form-row"><label>{t({ ja: '手当の金額（円）', en: 'Allowance amount (JPY)' })}<input className="input" name={`allowance${i}.amount`} inputMode="numeric" pattern="[0-9]+" required /></label><label>{t({ ja: '手当の根拠', en: 'Allowance basis' })}<input className="input" name={`allowance${i}.basis`} required maxLength={1000} /></label></div></div>)}<div className="button-row"><button type="button" className="btn" data-draft-change disabled={allowances >= 30} onClick={() => setAllowances(allowances + 1)}>{t({ ja: '手当を追加', en: 'Add allowance' })}</button>{allowances ? <button type="button" className="btn" data-draft-change onClick={() => setAllowances(allowances - 1)}>{t({ ja: '最後の手当を除く', en: 'Remove last allowance' })}</button> : null}</div></section>
    <label>{t({ ja: '確認記録・根拠', en: 'Review note and evidence' })}<textarea className="input" name="reason" required maxLength={1000} rows={3} /></label><label className="workforce-checkbox"><input type="checkbox" name="calculationConfirmed" required />{t({ ja: '勤怠・賃金条件・割増・手当・控除の根拠と計算を確認しました', en: 'I verified attendance, pay terms, premiums, allowances, deductions and their calculation' })}</label>
  </WorkforceDialog>;
}

export function WorkforcePayroll({ rows, actions, self = false, selfEmployeeId }: { rows: PayrollSummary[]; actions: string[]; self?: boolean; selfEmployeeId?: string }) {
  const { t } = useLocale(), task = useWorkforceTask();
  const [expanded, setExpanded] = useState<string>(), [confirm, setConfirm] = useState<PayrollSummary>(), [cancel, setCancel] = useState<PayrollSummary>();
  const visible = self ? rows.filter((row) => row.status === 'confirmed') : rows;
  return <WorkforcePanel title={t(self ? { ja: '給与明細', en: 'Payslips' } : { ja: '給与の計算・確定', en: 'Payroll calculations' })} note={t(self ? { ja: '確定された自分の明細を確認できます。', en: 'View your own confirmed payslips.' } : { ja: '未確認の控除をゼロで埋めず、根拠を確認して確定します。', en: 'Review the evidence for every deduction before confirming.' })} icon="document">
    {visible.length ? <div className="workforce-record-list">{visible.map((row) => <article className="workforce-record" key={row.id}><header><h3>{row.period} {self ? row.number : row.employeeName}</h3><WorkforceStatus status={row.status} /></header>{row.status === 'confirmed' ? <div className="workforce-record-meta"><span>{t({ ja: '差引支給額', en: 'Net pay' })}</span><WorkforceMoney value={row.netPay} /></div> : <div className="workforce-record-meta"><span>{t({ ja: '基本給・割増の計算済み', en: 'Base and premium calculated' })}</span><WorkforceMoney value={row.grossPay} /></div>}
      <div className="workforce-record-actions"><button type="button" className="btn" aria-expanded={expanded === row.id} onClick={() => setExpanded(expanded === row.id ? undefined : row.id)}>{t({ ja: '明細を見る', en: 'View details' })}</button>{!self && row.status === 'draft' && actions.includes('workforce.confirm_payroll') ? <button type="button" className="btn btn-primary" disabled={row.employeeId === selfEmployeeId} onClick={() => setConfirm(row)}>{t({ ja: '確認・確定', en: 'Review and confirm' })}</button> : null}{!self && row.status === 'confirmed' && actions.includes('workforce.cancel_payroll') ? <button type="button" className="btn" disabled={row.employeeId === selfEmployeeId} onClick={() => setCancel(row)}>{t({ ja: '給与を取り消す', en: 'Cancel payroll' })}</button> : null}</div>
      {expanded === row.id ? <PayrollBreakdown row={row} /> : null}
    </article>)}</div> : <WorkforceEmpty icon="document">{t(self ? { ja: '確定した給与明細はまだありません。公開されるとここに表示されます。', en: 'There are no confirmed payslips yet. They will appear here once published.' } : { ja: 'この月の給与計算はまだありません。承認済みの勤怠と賃金条件を確認して計算してください。', en: 'There are no payroll calculations this month. Review approved attendance and pay terms to begin.' })}</WorkforceEmpty>}
    {confirm ? <PayrollConfirm row={confirm} current={rows.find((r) => r.id === confirm.id)} onClose={() => setConfirm(undefined)} /> : null}
    {cancel ? <WorkforceDialog title={t({ ja: '給与を取り消す', en: 'Cancel payroll' })} description={cancel.employeeName + ' · ' + cancel.period} submitLabel={t({ ja: '取消を確定', en: 'Confirm cancellation' })} onClose={() => setCancel(undefined)} stale={rows.find((r) => r.id === cancel.id)?.version !== cancel.version} onSubmit={async (data) => { await task.mutateAsync({ action: 'workforce.cancel_payroll', input: { payrollId: cancel.id, expectedVersion: cancel.version, reason: formText(data, 'reason') } }); }}><label>{t({ ja: '取り消す理由', en: 'Cancellation reason' })}<textarea className="input" name="reason" required maxLength={1000} rows={3} /></label></WorkforceDialog> : null}
  </WorkforcePanel>;
}
