import { expect, test } from '@playwright/test';
import { commerceAction, commerceFixture, closeCommercePeriods } from './commerce-helpers.ts';
import { signInQuality, assertNoOverflow } from './quality-helpers.ts';
import { PASSWORD, api } from './operations-helpers.ts';
import { BUSINESS_DATE } from './environment.ts';
test.setTimeout(150_000);
test('FC declared monthly fee → invoice → full receipt → atomic cancellation through the UI', async ({ page, request }) => {
 const fixture = await commerceFixture(request); await signInQuality(page, fixture.email, PASSWORD); await page.goto('/commerce/franchise'); await expect(page.getByRole('heading', { name: 'FC月次精算', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'この契約で月次精算', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByLabel('精算月', { exact: true }).fill(fixture.period.month); await dialog.getByLabel('請求日', { exact: true }).fill(fixture.period.to); await dialog.getByLabel('税込売上（円）', { exact: true }).fill('110000'); await dialog.getByLabel('税抜売上（円）', { exact: true }).fill('100000'); await dialog.getByLabel('支払期日', { exact: true }).fill(BUSINESS_DATE); await dialog.getByLabel('確定売上資料・確認記録', { exact: true }).fill('承認済み合成月次売上表 UI-001');
 const made = await commerceAction(page, 'franchise.generate', () => dialog.getByRole('button', { name: '根拠を確認して請求を生成', exact: true }).click()); await expect(dialog).toHaveCount(0); await expect(page.locator('.commerce-metric').filter({ hasText: '現在の未決済残高' })).toContainText('6,000');
 await page.getByRole('button', { name: '2. 入出金を確認', exact: true }).click(); await dialog.getByRole('combobox', { name: '入出金科目', exact: true }).fill('普通預金'); await dialog.getByRole('option').filter({ hasText: '普通預金' }).click(); await commerceAction(page, 'franchise.settle', () => dialog.getByRole('button', { name: '入出金を確定', exact: true }).click()); await expect(dialog).toHaveCount(0); await expect(page.locator('.commerce-metric').filter({ hasText: '現在の未決済残高' }).locator('strong')).toHaveText(/0\s*円/);
 await page.screenshot({ path: test.info().outputPath('franchise-desktop.png'), fullPage: true }); await page.getByRole('button', { name: '精算を取消', exact: true }).click(); await dialog.getByLabel('取消理由', { exact: true }).fill('合成売上資料の訂正'); await commerceAction(page, 'franchise.cancel', () => dialog.getByRole('button', { name: '理由を記録して一括取消', exact: true }).click()); await expect(dialog).toHaveCount(0); const result = await api<{ status: string; balance: string }>(request, fixture.headers, '/actions/franchise.board', { settlementId: made.id }); expect(result.status).toBe('cancelled');
});
test('group company selection, account mapping, balanced elimination and reviewed confirmation work at 375px', async ({ page, request }) => {
 const f = await commerceFixture(request); await closeCommercePeriods(request, f); await page.setViewportSize({ width: 375, height: 812 }); await signInQuality(page, f.email, PASSWORD); await page.goto('/commerce/group'); await expect(page.getByRole('heading', { name: 'グループ連結精算表', exact: true })).toBeVisible();
 await page.getByRole('checkbox', { name: f.first.code + ' · ' + f.first.name, exact: true }).check(); await page.getByRole('checkbox', { name: f.second.code + ' · ' + f.second.name, exact: true }).check(); await page.getByLabel('開始日', { exact: true }).fill(f.period.from); await page.getByLabel('終了日', { exact: true }).fill(f.period.to); await page.getByRole('button', { name: '単体資料を取得', exact: true }).click(); await page.getByRole('button', { name: '2. 科目対応・消去を入力', exact: true }).click();
 const dialog = page.getByRole('dialog'); await dialog.getByLabel('精算表の名前', { exact: true }).fill('UI合成連結精算'); await dialog.getByRole('button', { name: '＋ 消去・調整を追加', exact: true }).click(); await dialog.getByLabel('摘要・根拠', { exact: true }).fill('合成内部取引100円を照合・消去'); await dialog.getByRole('combobox', { name: '調整1 行1 科目', exact: true }).selectOption('4000'); await dialog.getByLabel('調整1 行1 借方', { exact: true }).fill('100'); await dialog.getByRole('combobox', { name: '調整1 行2 科目', exact: true }).selectOption('1000'); await dialog.getByLabel('調整1 行2 貸方', { exact: true }).fill('100'); await dialog.getByLabel('連結範囲・根拠資料・確認事項', { exact: true }).fill('合成2会社、全単体資料・内部取引確認済'); await assertNoOverflow(page); await page.screenshot({ path: test.info().outputPath('group-mapping-mobile.png'), fullPage: true });
 await commerceAction(page, 'group_accounting.prepare', () => dialog.getByRole('button', { name: '照合資料と下書きを保存', exact: true }).click()); await expect(dialog).toHaveCount(0); await expect(page.locator('.commerce-metric').filter({ hasText: '連結借方合計' })).toContainText('1,900'); await page.getByRole('button', { name: '確定内容を確認', exact: true }).click(); await dialog.getByLabel('確認・取消理由', { exact: true }).fill('連結担当の確認完了'); await commerceAction(page, 'group_accounting.confirm', () => dialog.getByRole('button', { name: '確認して確定', exact: true }).click()); await expect(dialog).toHaveCount(0); await expect(page.locator('.commerce-metric').filter({ hasText: '精算表の状態' })).toContainText('確定済み'); await assertNoOverflow(page); await page.screenshot({ path: test.info().outputPath('group-confirmed-mobile.png'), fullPage: true });
});
test('POS shows explicit unconnected state and configured locations without pretending receipt success', async ({ page, request }) => { const f = await commerceFixture(request); await signInQuality(page, f.email, PASSWORD); await page.setViewportSize({ width: 375, height: 812 }); await page.goto('/commerce/pos'); await expect(page.getByRole('heading', { name: 'POS決済の自動連携', exact: true })).toBeVisible(); await expect(page.getByText('まだ通知を受信していません。未設定の連携を稼働中とは表示しません。')).toBeVisible(); await expect(page.getByText('合成Square店舗', { exact: false })).toBeVisible(); await assertNoOverflow(page); await page.screenshot({ path: test.info().outputPath('pos-mobile.png'), fullPage: true }); await page.setViewportSize({ width: 1280, height: 900 }); await page.getByRole('button', { name: '言語: en', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Automatic POS payment integration', exact: true })).toBeVisible(); await expect(page.getByRole('heading', { name: 'Inbox and retries', exact: true })).toBeVisible(); await expect(page.getByText('Active', { exact: true })).toBeVisible(); });

test('FC payment confirmation rejects a balance changed by another receipt and preserves the form', async ({ page, request }) => {
 const f = await commerceFixture(request), made = await api(request, f.headers, '/actions/franchise.generate', { agreementId: f.agreement.id, expectedAgreementVersion: f.agreement.version, month: f.period.month, grossSales: '100000', netSales: '100000', sourceReference: '残高競合検証', date: f.period.to, dueDate: BUSINESS_DATE });
 await signInQuality(page, f.email, PASSWORD); await page.goto('/commerce/franchise'); await page.getByRole('button', { name: '根拠と残高', exact: true }).click(); await page.getByRole('button', { name: '2. 入出金を確認', exact: true }).click(); const dialog = page.getByRole('dialog'); await dialog.getByRole('combobox', { name: '入出金科目', exact: true }).fill('普通預金'); await dialog.getByRole('option').filter({ hasText: '普通預金' }).click();
 const board = await api<{ invoiceId: string; contract: { partnerId: string } }>(request, f.headers, '/actions/franchise.board', { settlementId: made.id }); const external = await api(request, f.headers, '/api/payment', { direction: 'receive', partnerId: board.contract.partnerId, date: BUSINESS_DATE, amount: '1000', method: 'bank_transfer', accountId: f.accounts['1100'], lines: { payment_allocation: [{ invoiceEntity: 'sales_invoice', invoiceId: board.invoiceId, amount: '1000' }] } }); const current = await api(request, f.headers, '/api/payment/' + external.id); await api(request, f.headers, '/actions/payment.submit', { id: current.id, expectedVersion: current.version });
 const waiting = page.waitForResponse((r) => r.url().endsWith('/actions/franchise.settle')); await dialog.getByRole('button', { name: '入出金を確定', exact: true }).click(); expect((await waiting).status()).toBe(409); await expect(dialog.getByText('請求残高が確認時点から変わりました。', { exact: true })).toBeVisible(); await expect(dialog.getByRole('combobox', { name: '入出金科目', exact: true })).toHaveValue('普通預金'); const unchanged = await api<{ balance: string; paymentId: string | null }>(request, f.headers, '/actions/franchise.board', { settlementId: made.id }); expect(unchanged).toMatchObject({ balance: '5000', paymentId: null });
});
