import { defineDocument, defineEntity, f, label } from '@daifuku/kernel';
import { E, H, M, P, identityFields, owned, personPermissions, edit, read, reviewFields } from './common.ts';
export const WorkforcePayPolicy = defineEntity({
  name: 'workforce_pay_policy',
  label: label('勤怠・給与制度', 'Work and pay policies'),
  ext: false,
  siteAccess: { kind: 'sharedRead' },
  fields: {
    code: f.text({ required: true, unique: true, maxLength: 40, label: label('制度コード', 'Policy code') }),
    name: f.text({ required: true, maxLength: 100, label: label('制度名', 'Name') }),
    validFrom: f.date({ required: true, label: label('適用開始日', 'Valid from') }),
    validTo: f.date({ required: true, label: label('適用終了日', 'Valid to') }),
    workSystem: f.enum(['ordinary'], {
      required: true,
      default: 'ordinary',
      label: label('労働時間制', 'Working time system'),
    }),
    weekStartsOn: f.int({
      required: true,
      min: 0,
      max: 6,
      label: label('週の起算曜日（0日曜〜6土曜）', 'Week start (0 Sunday)'),
    }),
    dailyLimitMinutes: f.int({ required: true, min: 1, label: label('日通常時間上限（分）', 'Daily regular minutes') }),
    weeklyLimitMinutes: f.int({
      required: true,
      min: 1,
      label: label('週通常時間上限（分）', 'Weekly regular minutes'),
    }),
    breakAfterMinutes: f.int({
      required: true,
      min: 1,
      label: label('休憩必須となる勤務時間（超、分）', 'Break required after minutes'),
    }),
    breakMinutes: f.int({ required: true, min: 1, label: label('必要休憩（分）', 'Required break minutes') }),
    longBreakAfterMinutes: f.int({
      required: true,
      min: 1,
      label: label('長休憩必須となる勤務時間（超、分）', 'Long break required after minutes'),
    }),
    longBreakMinutes: f.int({ required: true, min: 1, label: label('必要長休憩（分）', 'Long break minutes') }),
    nightStartsMinute: f.int({
      required: true,
      min: 0,
      max: 1439,
      label: label('深夜開始（日の開始から分）', 'Night start minute'),
    }),
    nightEndsMinute: f.int({
      required: true,
      min: 0,
      max: 1439,
      label: label('深夜終了（日の開始から分）', 'Night end minute'),
    }),
    monthlyOvertimeThresholdMinutes: f.int({
      required: true,
      min: 1,
      label: label('高率時間外の月閾値（分）', 'Monthly high overtime threshold'),
    }),
    overtimePremiumRate: f.decimal({
      required: true,
      min: '0',
      scale: 4,
      label: label('時間外加算率', 'Overtime premium'),
    }),
    highOvertimePremiumRate: f.decimal({
      required: true,
      min: '0',
      scale: 4,
      label: label('高率時間外加算率', 'High overtime premium'),
    }),
    holidayPremiumRate: f.decimal({
      required: true,
      min: '0',
      scale: 4,
      label: label('法定休日加算率', 'Statutory holiday premium'),
    }),
    nightPremiumRate: f.decimal({ required: true, min: '0', scale: 4, label: label('深夜加算率', 'Night premium') }),
    basis: f.text({
      required: true,
      maxLength: 2000,
      multiline: true,
      label: label('制度根拠・就業規則', 'Policy basis'),
    }),
  },
  permissions: { roles: { [E]: read, [M]: read, [H]: edit, [P]: edit } },
  views: { list: ['code', 'name', 'validFrom', 'validTo'] },
});
export const WorkforcePayTerms = defineEntity({
  name: 'workforce_pay_terms',
  label: label('期間付き賃金条件', 'Effective pay terms'),
  ext: false,
  fields: {
    employeeId: f.ref('workforce_employee', { required: true, immutable: true, label: label('従業員', 'Employee') }),
    policyId: f.ref('workforce_pay_policy', { required: true, label: label('計算制度', 'Policy') }),
    validFrom: f.date({ required: true, label: label('適用開始日', 'Valid from') }),
    validTo: f.date({ required: true, label: label('適用終了日', 'Valid to') }),
    payType: f.enum(['hourly', 'monthly'], { required: true, label: label('時給・月給', 'Pay type') }),
    hourlyRate: f.money({
      required: true,
      min: '0',
      label: label('時給額（月給時は0）', 'Hourly rate (zero for monthly)'),
    }),
    monthlySalary: f.money({
      required: true,
      min: '0',
      label: label('月給額（時給時は0）', 'Monthly salary (zero for hourly)'),
    }),
    monthlyBaseMinutes: f.int({
      required: true,
      min: 1,
      label: label('月給の割増基礎となる月所定分', 'Monthly premium divisor minutes'),
    }),
    paidLeaveDayMinutes: f.int({
      required: true,
      min: 1,
      max: 1440,
      label: label('全日有給の通常賃金換算分', 'Minutes per paid leave day'),
    }),
    confirmed: f.bool({ required: true, label: label('雇用条件・割増基礎の確認', 'Employment terms confirmed') }),
    basis: f.text({ required: true, maxLength: 2000, multiline: true, label: label('賃金条件根拠', 'Terms basis') }),
  },
  indexes: [['employeeId', 'validFrom', 'validTo']],
  permissions: { roles: { [P]: edit } },
  views: { list: ['employeeId', 'payType', 'validFrom', 'validTo', 'hourlyRate', 'monthlySalary'] },
});
export const WorkforcePayroll = defineDocument({
  name: 'workforce_payroll',
  label: label('給与計算・明細', 'Payroll and payslips'),
  ext: false,
  siteAccess: { kind: 'store', field: 'siteId' },
  naming: { type: 'sequence', prefix: 'PAY-', period: 'year' },
  fields: {
    ...identityFields(),
    period: f.text({
      ...owned,
      required: true,
      immutable: true,
      pattern: /^\d{4}-(0[1-9]|1[0-2])$/,
      maxLength: 7,
      label: label('対象月', 'Pay month'),
    }),
    periodStart: f.date({ ...owned, required: true, immutable: true }),
    periodEnd: f.date({ ...owned, required: true, immutable: true }),
    termsId: f.ref('workforce_pay_terms', { ...owned, required: true }),
    basePay: f.money({ ...owned, required: true, min: '0', label: label('通常賃金', 'Base pay') }),
    premiumPay: f.money({ ...owned, required: true, min: '0', label: label('割増賃金', 'Premium pay') }),
    grossPay: f.money({ ...owned, required: true, min: '0', label: label('総支給', 'Gross pay') }),
    deductionTotal: f.money({
      ...owned,
      required: true,
      default: '0',
      min: '0',
      label: label('控除合計（未確認は下書き）', 'Deductions (draft until confirmed)'),
    }),
    netPay: f.money({ ...owned, required: true, default: '0', min: '0', label: label('差引支給', 'Net pay') }),
    workedMs: f.int({ ...owned, required: true, min: 0, hidden: true }),
    paidLeaveDays: f.decimal({ ...owned, required: true, min: '0', scale: 1 }),
    allowances: f.json({ ...owned, required: true, default: [], label: label('手当明細', 'Allowances') }),
    deductions: f.json({ ...owned, required: true, default: [], label: label('控除明細', 'Deductions') }),
    calculation: f.json({ ...owned, required: true, label: label('計算再現資料', 'Calculation evidence') }),
    sourceFingerprint: f.text({ ...owned, required: true, hidden: true }),
    attendanceCompleteConfirmed: f.bool({ ...owned, required: true, immutable: true }),
    calculationConfirmed: f.bool({ ...owned, required: true, default: false }),
    ...reviewFields(),
  },
  allowOnSubmit: ['reviewedBy', 'reviewedAt', 'reviewReason'],
  indexes: [['employeeId', 'period']],
  permissions: personPermissions(
    { employee: read, manager: read, hr: read, payroll: ['read', 'create', 'update', 'submit', 'cancel', 'export'] },
    true,
  ),
  views: { list: ['employeeId', 'period', 'grossPay', 'deductionTotal', 'netPay'] },
});
/** Minimal operational period boundary; managers need closed dates, never payroll amounts. */
export const WorkforcePeriodLock = defineEntity({
  name: 'workforce_period_lock',
  label: label('従業員の確定期間', 'Closed employee periods'),
  ext: false,
  siteAccess: { kind: 'parent', field: 'employeeId', entity: 'workforce_employee' },
  fields: {
    ...identityFields(),
    payrollId: f.ref('workforce_payroll', { ...owned, required: true, immutable: true }),
    periodStart: f.date({ ...owned, required: true, immutable: true }),
    periodEnd: f.date({ ...owned, required: true, immutable: true }),
    active: f.bool({ ...owned, required: true, default: true }),
  },
  unique: [['payrollId']],
  indexes: [['employeeId', 'active', 'periodStart']],
  permissions: personPermissions({
    employee: read,
    manager: read,
    hr: read,
    payroll: ['read', 'create', 'update', 'export'],
  }),
  views: { list: ['employeeId', 'periodStart', 'periodEnd', 'active'] },
});
