import { useState } from 'react';
import { bankBoardOutput, type BankBoard } from '@daifuku/mod-banking/contract';
import { financeIdentity, useFinanceAccess, useFinanceRead } from '../api/finance.ts';
import { useLocale } from '../i18n.tsx';
import { FinanceEmpty, FinanceMoney, FinanceNotice, FinancePanel, FinanceShell, FinanceSteps, SourceLink } from '../components/finance-shared.tsx';
import { BankingAccountForm, type BankingEdit } from '../components/banking-accounts.tsx';
import { BankingImport } from '../components/banking-import.tsx';
import { BankingMatch, BankingUndo } from '../components/banking-match.tsx';
import { BankingTransferCancel, BankingTransferExport, BankingTransferPrepare } from '../components/banking-transfers.tsx';
import { CommercePager } from '../components/commerce-shared.tsx';

type Dialog = { type: 'edit'; edit: BankingEdit } | { type: 'import' | 'prepare'; account: BankBoard['accounts'][number] } | { type: 'match'; statementId: string } | { type: 'undo'; row: BankBoard['reconciliations'][number] } | { type: 'export'; batchId: string } | { type: 'cancel'; row: BankBoard['transfers'][number] };
export function BankingPage() { return <BankingWorkspace key={financeIdentity()}/>; }
function BankingWorkspace() {
  const { t } = useLocale(), access = useFinanceAccess(), actions = access.data?.actions.map((action) => action.name) ?? [], allowed = actions.includes('banking.board');
  const [accountId, setAccountId] = useState(''), [offset, setOffset] = useState(0), [tab, setTab] = useState<'match' | 'transfers' | 'accounts'>('match'), [dialog, setDialog] = useState<Dialog>();
  const query = useFinanceRead('banking.board', { ...(accountId ? { bankAccountId: accountId } : {}), offset }, allowed, bankBoardOutput.parse), data = query.data, account = data?.accounts.find((row) => row.id === accountId);
  const sources = [access, query], busy = sources.some((source) => source.isFetching || source.isError), stale = !allowed || sources.some((source) => source.isError), close = () => setDialog(undefined);
  return <FinanceShell title={{ ja: '銀行連携・消込', en: 'Banking and reconciliation' }} subtitle={{ ja: '銀行明細と請求・入出金を照合。振込準備と実際の出金を、一つずつ確かめながら進めます。', en: 'Match bank transactions to invoices and payments. Prepare transfers and verify actual debits with a clear record.' }} eyebrow="BANKING" allowed={allowed} ready={Boolean(access.data)} sources={sources}>
    <FinanceSteps steps={[{ ja: '口座を登録', en: 'Register accounts' }, { ja: '明細を取込', en: 'Import transactions' }, { ja: '根拠を照合', en: 'Review matches' }, { ja: '確認して消込', en: 'Confirm reconciliation' }]}/>
    <div className="finance-toolbar"><div className="finance-tabs">{(['match', 'transfers', 'accounts'] as const).map((value) => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)}>{t(value === 'match' ? { ja: '銀行明細', en: 'Transactions' } : value === 'transfers' ? { ja: '振込準備', en: 'Transfers' } : { ja: '口座設定', en: 'Accounts' })}</button>)}</div><button className="btn" disabled={sources.some((source) => source.isFetching)} onClick={() => { for (const source of sources) void source.refetch(); }}>{t({ ja: '最新の状況を取得', en: 'Refresh' })}</button></div>
    {tab !== 'accounts' ? <div className="finance-toolbar"><label className="finance-field"><span>{t({ ja: '自社の銀行口座', en: 'Company bank account' })}</span><select className="input" value={accountId} onChange={(event) => { setAccountId(event.target.value); setOffset(0); }}><option value="">{t({ ja: 'すべての口座', en: 'All accounts' })}</option>{data?.accounts.map((row) => <option key={row.id} value={row.id}>{row.name} · {row.accountNumberMasked}</option>)}</select></label><div className="finance-buttons">{actions.includes('banking.import_statement_csv') ? <button className="btn btn-primary" disabled={busy || !account?.active} onClick={() => { if (account) setDialog({ type: 'import', account }); }}>{t({ ja: '明細CSVを取込', en: 'Import CSV' })}</button> : null}{actions.includes('banking.prepare_transfer') ? <button className="btn" disabled={busy || !account?.active} onClick={() => { if (account) setDialog({ type: 'prepare', account }); }}>{t({ ja: '振込データを準備', en: 'Prepare transfers' })}</button> : null}</div></div> : null}
    {!data ? <p role="status">{t({ ja: '銀行データを取得しています…', en: 'Loading banking data…' })}</p> : <>
      {data.accounts.length === 0 ? <FinanceNotice>{t({ ja: '「口座設定」で自社口座と勘定科目を登録すると、明細取込を開始できます。', en: 'Register a company bank account and its ledger account in Accounts to start importing.' })}</FinanceNotice> : null}
      {tab === 'match' ? <FinancePanel title={t({ ja: '銀行明細と照合状況', en: 'Transactions and reconciliation' })} note={t({ ja: '候補の提示だけでは記帳しません。請求書または既存入出金との関係を確認します。', en: 'Suggestions do not post entries. Review the invoice or existing payment before confirming.' })}><BankStatements data={data} busy={busy} onDialog={setDialog}/><CommercePager offset={offset} total={data.statementTotal} onPage={setOffset}/></FinancePanel> : null}
      {tab === 'transfers' ? <FinancePanel title={t({ ja: '振込準備の履歴', en: 'Transfer preparation history' })} note={t({ ja: '「出力済み」はファイルを作成した状態です。銀行受付・送金成功を表しません。', en: 'Exported means a file was created. It does not confirm bank acceptance or a successful transfer.' })}><BankTransfers data={data} busy={busy} onDialog={setDialog}/></FinancePanel> : null}
      {tab === 'accounts' ? <BankAccounts data={data} busy={busy} onDialog={setDialog}/> : null}
      {Object.values(data.truncated).some(Boolean) ? <FinanceNotice>{t({ ja: '件数の多い一覧は一部を表示しています。明細はページを切り替え、口座で絞り込んでください。', en: 'Large lists show a subset. Page through transactions and filter by account.' })}</FinanceNotice> : null}
      {dialog?.type === 'edit' ? <BankingAccountForm edit={dialog.edit} stale={stale} onClose={close}/> : dialog?.type === 'import' ? <BankingImport account={dialog.account} stale={stale} onClose={close}/> : dialog?.type === 'match' ? <BankingMatch statementId={dialog.statementId} stale={stale} onClose={close}/> : dialog?.type === 'undo' ? <BankingUndo row={dialog.row} stale={stale} onClose={close}/> : dialog?.type === 'prepare' ? <BankingTransferPrepare account={dialog.account} payees={data.payees} stale={stale} onClose={close}/> : dialog?.type === 'export' ? <BankingTransferExport batchId={dialog.batchId} stale={stale} onClose={close}/> : dialog?.type === 'cancel' ? <BankingTransferCancel row={dialog.row} stale={stale} onClose={close}/> : null}
    </>}
    <FinanceNotice>{t({ ja: '現在はファイルによる連携です。銀行APIの常時接続、振込の実行、手数料の自動相殺は行いません。', en: 'This workspace uses file exchange. It does not maintain a bank API connection, execute transfers or automatically offset fees.' })}</FinanceNotice>
  </FinanceShell>;
}

function BankStatements({ data, busy, onDialog }: { data: BankBoard; busy: boolean; onDialog: (dialog: Dialog) => void }) {
  const { t } = useLocale();
  return data.statements.length === 0 ? <FinanceEmpty>{t({ ja: 'まだ明細がありません。対象口座を選んでCSVを取り込んでください。', en: 'No transactions yet. Select an account and import a CSV.' })}</FinanceEmpty> : <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>{t({ ja: '日付・明細ID', en: 'Date / reference' })}</th><th>{t({ ja: '摘要', en: 'Description' })}</th><th>{t({ ja: '入出金額', en: 'Amount' })}</th><th>{t({ ja: '照合', en: 'Reconciliation' })}</th></tr></thead><tbody>{data.statements.map((row) => { const match = data.reconciliations.find((entry) => entry.id === row.reconciliationId); return <tr key={row.id}><td>{row.bookedOn}<small>{row.externalId}</small></td><td>{row.description}<small>{data.accounts.find((item) => item.id === row.bankAccountId)?.name}</small></td><td data-money>{row.direction === 'receive' ? '+' : '−'}<FinanceMoney value={row.amount}/></td><td>{row.state === 'unmatched' ? <button className="btn btn-primary" disabled={busy} onClick={() => onDialog({ type: 'match', statementId: row.id })}>{t({ ja: '照合候補を確認', en: 'Review matches' })}</button> : <><SourceLink entity="payment" id={row.paymentId}>{t({ ja: '照合済み入出金', en: 'Reconciled payment' })}</SourceLink>{match ? <button className="btn" disabled={busy} onClick={() => onDialog({ type: 'undo', row: match })}>{t({ ja: '解除', en: 'Reverse' })}</button> : null}</>}</td></tr>; })}</tbody></table></div>;
}

function BankTransfers({ data, busy, onDialog }: { data: BankBoard; busy: boolean; onDialog: (dialog: Dialog) => void }) {
  const { t } = useLocale();
  return data.transfers.length === 0 ? <FinanceEmpty>{t({ ja: '振込準備はまだありません。自社口座を選んで準備を開始してください。', en: 'No transfer batches yet. Select a company account to prepare one.' })}</FinanceEmpty> : <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>{t({ ja: '指定日・件数', en: 'Date / items' })}</th><th>{t({ ja: '合計', en: 'Total' })}</th><th>{t({ ja: '状態', en: 'Status' })}</th><th>{t({ ja: '操作', en: 'Actions' })}</th></tr></thead><tbody>{data.transfers.map((row) => <tr key={row.id}><td>{row.transferDate}<small>{row.itemCount} {t({ ja: '件', en: 'items' })}</small></td><td data-money><FinanceMoney value={row.total}/></td><td><span className="finance-badge">{t(row.state === 'prepared' ? { ja: '準備済み', en: 'Prepared' } : row.state === 'exported' ? { ja: '出力済み・送金未確認', en: 'Exported / transfer unverified' } : { ja: '取消済み', en: 'Cancelled' })}</span></td><td>{row.state !== 'cancelled' ? <div className="finance-buttons"><button className="btn btn-primary" disabled={busy} onClick={() => onDialog({ type: 'export', batchId: row.id })}>{t({ ja: '確認・出力', en: 'Review / export' })}</button><button className="btn" disabled={busy} onClick={() => onDialog({ type: 'cancel', row })}>{t({ ja: '準備を取消', en: 'Cancel preparation' })}</button></div> : row.cancelReason}</td></tr>)}</tbody></table></div>;
}

function BankAccounts({ data, busy, onDialog }: { data: BankBoard; busy: boolean; onDialog: (dialog: Dialog) => void }) {
  const { t } = useLocale();
  return <div className="finance-grid"><FinancePanel title={t({ ja: '自社の銀行口座', en: 'Company accounts' })} actions={<button className="btn btn-primary" disabled={busy} onClick={() => onDialog({ type: 'edit', edit: { type: 'account' } })}>{t({ ja: '自社口座を登録', en: 'Add company account' })}</button>}><div className="commerce-list">{data.accounts.map((row) => <article className="commerce-list-item" key={row.id}><div><strong>{row.name}</strong><small>{row.bankCode}-{row.branchCode} · {row.accountNumberMasked}</small><small>{row.active ? t({ ja: '有効', en: 'Active' }) : t({ ja: '無効', en: 'Inactive' })}</small></div><button className="btn" disabled={busy} onClick={() => onDialog({ type: 'edit', edit: { type: 'account', row } })}>{t({ ja: '編集', en: 'Edit' })}</button></article>)}</div></FinancePanel><FinancePanel title={t({ ja: '取引先の振込口座', en: 'Payee accounts' })} actions={<button className="btn btn-primary" disabled={busy} onClick={() => onDialog({ type: 'edit', edit: { type: 'payee' } })}>{t({ ja: '振込先を登録', en: 'Add payee' })}</button>}><div className="commerce-list">{data.payees.map((row) => <article className="commerce-list-item" key={row.id}><div><strong>{row.partnerName}</strong><small>{row.holderKana} · {row.accountNumberMasked}</small><small>{row.active ? t({ ja: '有効', en: 'Active' }) : t({ ja: '無効', en: 'Inactive' })}</small></div><button className="btn" disabled={busy} onClick={() => onDialog({ type: 'edit', edit: { type: 'payee', row } })}>{t({ ja: '編集', en: 'Edit' })}</button></article>)}</div></FinancePanel></div>;
}
